# -*- coding: utf-8 -*-
"""
Created on Tue May 26 09:37:02 2026

@author: francesca.boschi
"""
import pandas as pd
from pathlib import Path
import json




class CollectorCSV:
    """
    Collect session-level CSV and JSON outputs for one patient.

    This class is used before downstream DMO analysis. It loads the outputs
    generated by the previous pipeline steps, including stride-level parameters,
    walking-bout tables, walking-bout pauses, and processing logs.

    The collector can load data for one recording date or for all recording
    dates available inside the patient directory.

    Expected folder structure
    -------------------------
    patient_directory/
        YYYY-MM-DD/
            session_id/
                PATIENT_session_id_YYYY-MM-DD_parameters.csv
                PATIENT_session_id_YYYY-MM-DD_log.json
                PATIENT_session_id_YYYY-MM-DD_wb_dataframe.csv
                PATIENT_session_id_YYYY-MM-DD_wb_pauses_dataframe.csv

    Parameters
    ----------
    patient_id : str
        Patient or participant identifier.

    date : str
        Recording date to collect. Use a specific date, for example
        ``"2023-07-14"``, or use ``"all"`` to collect all available dates.

    patient_directory : str or pathlib.Path
        Path to the patient folder containing one subfolder per recording date.
    """

    def __init__(self, patient_id, date, patient_directory):
        """
        Initialize the collector for one patient and one date selection.
        """

        self.patient_id = patient_id
        self.date = date
        self.patient_directory = Path(patient_directory)

        self.parameters = pd.DataFrame()
        self.wb_dataframe = pd.DataFrame()
        self.wb_pauses_dataframe = pd.DataFrame()
        self.log = []

        self.selected_dates = []
        self.missing_files = []

    def _get_dates_to_collect(self):
        """
        Return the list of recording dates that should be collected.
        """
    
        if not self.patient_directory.exists():
            raise FileNotFoundError(
                f"Patient directory not found: {self.patient_directory}"
            )
    
        # Case 1: collect all date folders
        if self.date == "all":
            dates = []
    
            for folder in self.patient_directory.iterdir():
                if not folder.is_dir():
                    continue
    
                try:
                    pd.to_datetime(folder.name, format="%Y-%m-%d")
                    dates.append(folder.name)
                except ValueError:
                    continue
    
            dates = sorted(dates)
    
            if not dates:
                raise FileNotFoundError(
                    f"No date folders found in: {self.patient_directory}"
                )
    
            return dates
    
        # Case 2: collect one date
        if isinstance(self.date, str):
            requested_dates = [self.date]
    
        # Case 3: collect a list of dates
        elif isinstance(self.date, list):
            requested_dates = self.date
    
        else:
            raise TypeError(
                "date must be a string, a list of strings, or 'all'."
            )
    
        missing_dates = []
    
        for recording_date in requested_dates:
            date_folder = self.patient_directory / recording_date
    
            if not date_folder.exists():
                missing_dates.append(recording_date)
    
        if missing_dates:
            raise FileNotFoundError(
                f"Date folder(s) not found: {missing_dates}"
            )
    
        return requested_dates
    def collect(self):
        """
        Load and concatenate available CSV and JSON outputs.

        For each selected date, the method scans all session folders and loads
        the parameters, walking-bout dataframe, walking-bout pauses, and log file
        when available.
        """

        parameters_list = []
        wb_list = []
        pauses_list = []
        log_list = []
        self.missing_files = []

        self.selected_dates = self._get_dates_to_collect()

        for recording_date in self.selected_dates:

            date_folder = self.patient_directory / recording_date

            for session_folder in date_folder.iterdir():
                if not session_folder.is_dir():
                    continue

                session_id = session_folder.name
                base_name = f"{self.patient_id}_{session_id}_{recording_date}"

                parameters_file = session_folder / f"{base_name}_parameters.csv"
                log_file = session_folder / f"{base_name}_log.json"
                wb_file = session_folder / f"{base_name}_wb_dataframe.csv"
                pauses_file = session_folder / f"{base_name}_wb_pauses_dataframe.csv"
                
                if parameters_file.exists():
                    df = pd.read_csv(parameters_file)
                    df["patient_id"] = self.patient_id
                    df["recording_date"] = recording_date
                    df["session_id"] = session_id
                    parameters_list.append(df)
                else:
                    self.missing_files.append({
                        "recording_date": recording_date,
                        "session_id": session_id,
                        "missing_file": "parameters",
                        "expected_path": str(parameters_file),
                    })
                
                if wb_file.exists():
                    df = pd.read_csv(wb_file)
                    df["patient_id"] = self.patient_id
                    df["recording_date"] = recording_date
                    df["session_id"] = session_id
                    wb_list.append(df)
                else:
                    self.missing_files.append({
                        "recording_date": recording_date,
                        "session_id": session_id,
                        "missing_file": "wb_dataframe",
                        "expected_path": str(wb_file),
                    })
                
                if pauses_file.exists():
                    df = pd.read_csv(pauses_file)
                    df["patient_id"] = self.patient_id
                    df["recording_date"] = recording_date
                    df["session_id"] = session_id
                    pauses_list.append(df)
                else:
                    self.missing_files.append({
                        "recording_date": recording_date,
                        "session_id": session_id,
                        "missing_file": "wb_pauses_dataframe",
                        "expected_path": str(pauses_file),
                    })

                if log_file.exists():
                    with open(log_file, "r", encoding="utf-8") as f:
                        log_data = json.load(f)
                
                    log_list.append({
                        "patient_id": self.patient_id,
                        "recording_date": recording_date,
                        "session_id": session_id,
                        "log": log_data,
                    })
                else:
                    self.missing_files.append({
                        "recording_date": recording_date,
                        "session_id": session_id,
                        "missing_file": "log",
                        "expected_path": str(log_file),
                    })

        if parameters_list:
            self.parameters = pd.concat(parameters_list, ignore_index=True)

        if wb_list:
            self.wb_dataframe = pd.concat(wb_list, ignore_index=True)

        if pauses_list:
            self.wb_pauses_dataframe = pd.concat(pauses_list, ignore_index=True)

        self.log = log_list

        return self

    def summary(self):
        """
        Print a compact summary of the collected data, grouped by date and session.
        """
    
        print(f"Patient: {self.patient_id}")
        print(f"Date selection: {self.date}")
        print(f"Patient folder: {self.patient_directory}")
    
        print("\nSelected dates and sessions:")
    
        if not self.selected_dates:
            print("  No dates selected. Run collect() first.")
        else:
            for recording_date in self.selected_dates:
                sessions = set()
    
                if not self.parameters.empty:
                    mask = self.parameters["recording_date"] == recording_date
                    sessions.update(self.parameters.loc[mask, "session_id"].dropna().astype(str))
    
                if not self.wb_dataframe.empty:
                    mask = self.wb_dataframe["recording_date"] == recording_date
                    sessions.update(self.wb_dataframe.loc[mask, "session_id"].dropna().astype(str))
    
                if not self.wb_pauses_dataframe.empty:
                    mask = self.wb_pauses_dataframe["recording_date"] == recording_date
                    sessions.update(self.wb_pauses_dataframe.loc[mask, "session_id"].dropna().astype(str))
    
                for log_item in self.log:
                    if log_item["recording_date"] == recording_date:
                        sessions.add(str(log_item["session_id"]))
    
                sessions = sorted(sessions)
    
                if sessions:
                    print(f"  {recording_date}: {', '.join(sessions)}")
                else:
                    print(f"  {recording_date}: no sessions loaded")
    
        print("\nLoaded data:")
        print(f"  parameters rows: {len(self.parameters)}")
        print(f"  wb_dataframe rows: {len(self.wb_dataframe)}")
        print(f"  wb_pauses_dataframe rows: {len(self.wb_pauses_dataframe)}")
        print(f"  logs loaded: {len(self.log)}")
    
        print("\nMissing files:")
    
        if not self.missing_files:
            print("  None")
        else:
            missing_df = pd.DataFrame(self.missing_files)
    
            for recording_date in sorted(missing_df["recording_date"].unique()):
                print(f"  {recording_date}")
    
                date_df = missing_df[missing_df["recording_date"] == recording_date]
    
                for session_id in sorted(date_df["session_id"].unique()):
                    session_df = date_df[date_df["session_id"] == session_id]
                    missing_names = session_df["missing_file"].tolist()
    
                    print(f"    {session_id}: {', '.join(missing_names)}")